# Generated by Django 2.0.8 on 2018-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='person',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
