# Generated by Django 2.0.8 on 2018-09-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfBackend', '0002_auto_20180929_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='username',
        ),
    ]
