# Generated by Django 2.0.8 on 2018-09-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfBackend', '0005_auto_20180929_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lat',
            field=models.DecimalField(decimal_places=25, max_digits=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='long',
            field=models.DecimalField(decimal_places=25, max_digits=50),
        ),
    ]
